# Generated by Django 5.0 on 2023-12-30 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_applicationuser_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="renteruser",
            name="application_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
