# Generated by Django 5.0 on 2023-12-30 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0003_alter_applicationuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renteruser",
            name="application_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
