# Generated by Django 5.0 on 2023-12-30 11:30

import base_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0004_alter_renteruser_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationuser",
            name="user_id",
            field=models.CharField(
                default="44daac5370cc49c289251f583a2960a8",
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "admin_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "application_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenterRegisterRequests",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data_generated_on", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "application_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RenterRegisterResults",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data_generated_on", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField()),
                (
                    "renter_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.renterregisterrequests",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.adminuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
