# Generated by Django 5.0 on 2023-12-30 11:32

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_alter_applicationuser_user_id_adminuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationuser",
            name="user_id",
            field=models.CharField(
                default=base_app.models.generate_uuid,
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
